### PR TITLE
Docs: Added change log section.

### PR DESCRIPTION
**Pull request by andy-maier**
The changes since 0.4.0 in the new "Change log" section are supposed to be up to date.

Please review.

### CODE REVIEW

**Comment by andy-maier** [comment]
+1

**Comment by preethipy** [comment]
The change log looks good except for that i am confused with the version numbering. 0.4.0 seems to be a older release Released: 2016-09-13 while for 0.3.0 it says Released: Not yet

I thought 0.4.0 should be a later release than 0.3.0. Please clarify

**Comment by andy-maier** [comment]
I don't see a version 0.3.0 in the `docs/changes.rst` file. The version number of the current version being developed is automatically inserted by using `|version|`, and that is the version that says "Not yet released".

Can you please check again where you saw the 0.3.0 version?

**Comment by preethipy** [comment]
I just checked it again.. I see Version 0.4.1.dev20
May be i was doing something wrong...

**Pull request merged**
