### PR TITLE
Second chunk of Pylint issue resolutions that were not errors

### PR DESCRIPTION
**Pull request by andy-maier**
See commit message.

### CODE REVIEW

**Comment by andy-maier** [comment]
The decrease in coverage surprised me and it turns out that pytest issues a lot of warnings:
```
/Users/maiera/virtualenvs/zhmc38/lib/python3.8/site-packages/_pytest/mark/structures.py:335
  /Users/maiera/virtualenvs/zhmc38/lib/python3.8/site-packages/_pytest/mark/structures.py:335: PytestCollectionWarning: cannot collect 'test_connectionerror_str_def' because it is not a function.
    def __call__(self, *args: object, **kwargs: object):  # noqa: F811
```
It seems that pytest does not support static test methods, unfortunately.
I will have to change that again.

**Comment by andy-maier** [comment]
I have updated the PR to remove the `@staticmethod` decorator again from any test methods, and instead changed them to become global functions. Also, I removed the pinning of pylint to <2.5.0 because the issues in 2.5.0 have been addressed meanwhile.

**Comment by vkahir** [comment]
It is interesting to know about pytest does not support static test methods. Thanks for the update Andy

**Comment by mhartmay** [comment]
> I have updated the PR to remove the `@staticmethod` decorator again from any test methods, and instead changed them to become global functions. Also, I removed the pinning of pylint to <2.5.0 because the issues in 2.5.0 have been addressed meanwhile (and using 2.4.4 issues some useless warnings that 2.5.x does not issue).

Where did you find this information? At least what I've found is that staticmethods can be tested (see https://github.com/pytest-dev/pytest/pull/2531/files). Otherwise, this sounds like a bug in pytest. And to me the functions `create_session_1` and `create_session_2` look like they are candidates for a pytest fixture (see https://docs.pytest.org/en/stable/fixture.html).

**Pull request merged**
