### PR TITLE
Support for specifiying ports

### PR DESCRIPTION
**Pull request by mhartmay**
Add support for specifying the used JMS/STOMP and HMC ports.

### CODE REVIEW

**Comment by andy-maier** [comment]
@mhartmay The ports for the WS API and for JMS over STOMP are not configurable on the HMC. What is the purpose of making them configurable in the zhmcclient?

**Comment by mhartmay** [comment]
> @mhartmay The ports for the WS API and for JMS over STOMP are not configurable on the HMC. What is the purpose of making them configurable in the zhmcclient?

Sometimes local port forwarding is needed, for example if you need SSH tunneling to access the HMC. When you're now trying to access multiple HMCs in parallel there is a port clash.

**Comment by andy-maier** [comment]
Preliminary review: This PR introduces new optional `port` parameters to the `Session` and `NotificationReceiver` init methods. The implementation for that is fine.

**Discussion point:** The open discussion item is whether we want to go in that direction, as opposed to getting the port as part of the `host` parameter, using the standard URL syntax: `host:port`. This alternative would allow not having to change the higher levels of code sitting on top of the zhmcclient library (i.e. the zhmc CLI, and the zhmc Ansible modules, and the Ansible roles and playbooks using these modules). We'll discuss that in the zhmcclient team.

**Comment by andy-maier** [comment]
I talked with several people and did not find that people have a strong preference between adding a new parameter vs. adding the port to the host string. Given that for IPv6 addresses, the URL notation is not backwards compatible to a hostname or IP address (in the URL there are square brackets around the IP address), I have a preference for the separate port parameter as implemented in the PR. Inthe layers above the client library, we can still start supporting URLs if we wanted to.

**Comment by andy-maier** [comment]
I reviewed the code and it is fine. Merging.

**Comment by mhartmay** [comment]
Thanks a lot!

**Pull request merged**
