### PR TITLE
CLI: Add "metrics" command group

### PR DESCRIPTION
**Pull request by leopoldjuergen**
- Report CPC metrics: zhmc metrics cpc <CPC>
  This command provides metrics returned by the
  Metric Group 'cpc-usage-overview' for a not
  in DPM enabled CPC and provides metrics returned
  by the Metrics Group 'dpm-system-usage-overview'
  for a DPM enabled CPC.
- Report metrics of Partitions of a CPC:
  zhmc metrics partitions <CPC>
  This command provides metrics returned by the
  Metric Group 'partition-usage'.
- Report metrics of LPARs of a CPC:
  zhmc metrics lpars <CPC>
  This command provides metrics returned by the
  Metric Group 'logical-partition-usage'.

Signed-off-by: Juergen Leopold <leopoldj@de.ibm.com>

### CODE REVIEW

**Comment by andy-maier** [comment]
This PR should be rebased on PR #134, because it does not work without  it.

**Comment by andy-maier** [comment]
Can we have the command hierarchy for listing metrics switched around?

From:
* ``zhmc metrics cpc``

To:
* ``zhmc cpc metrics``

This would make it more consistent with the existing commands.

**Comment by andy-maier** [comment]
Comment 2: Can we show the metrics units in the metrics output?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6de55f9c96f9b3cdd1f674393afed91ae3ea9b93
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/python-zhmcclient/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6de55f9c96f9b3cdd1f674393afed91ae3ea9b93
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/python-zhmcclient/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6de55f9c96f9b3cdd1f674393afed91ae3ea9b93
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/python-zhmcclient/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b57c9fa5ade2893961eecc06cdefc88197549dd1
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/python-zhmcclient/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3a6ecf3f1c191c28574f4fee55822c9460b4d607
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/python-zhmcclient/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Comment by andy-maier** [comment]
From my perspective, the Metrics CLI is ready to be reviewed and merged.

**Pull request merged**
