### PR TITLE
Update  README.rst.

### PR DESCRIPTION
**Pull request by leopoldjuergen**
Signed-off-by: Juergen Leopold <leopoldj@de.ibm.com>

### CODE REVIEW

**Comment by andy-maier** [comment]
Comments on the README page as it is now (not just on the changes proposed in this PR):

1. The "Overview" section could be streamlined. I have updated the the "What this package provides" section of the Sphinx documentation in PR #37, and suggest to replace the content of the "Overview" section in the README.rst file with the first two paragraphs of the "What this package provides" section of PR #37.

2. Rename "Install" heading to "Installation".

3. In the "Install" section, I suggest to add a statement that the pip install also installs any dependendent packages.

4. In the "Install" section, the link to the install section should change its URL from "install.html" to "intro.html#installation", and should be moved into the text (i.e. a part of the text is the link label).

**Comment by leopoldjuergen** [comment]
+1

**Comment by andy-maier** [comment]
Remaining comments, based on commit ab335ba:

1. Typo in section title "Installtion".

2. The link to the install section is incorrect. Replace "install.html" with "intro.html#installation". In addition, you could make the link part of the text, so that the long URL is not shown.

**Comment by andy-maier** [comment]
+1

**Pull request merged**
