### PR TITLE
New Proposal for a command line interface for the zhmcclient

### PR DESCRIPTION
**Pull request by leopoldjuergen**
Details:
- Use the click (http://click.pocoo.org/5/) framework
  (decorator style implementation) for building
  command line interface (name: zhmc).
  See also 'why click ?' http://click.pocoo.org/5/why/
- zhmc will be installed together with the zhmcclient
  python bindings.
- Help for command line tool zhmc:
  zhmc --help
- Following commands are implemented:
  - General: info, api-version
  - Session: create, delete
  - CPC: list, show
  - LPARs: list, show, activate, deactivate
  - Partitions: create, delete, start, stop list,
                show
- General Flow:
  command line client for the zhmcclient.

  zhmc is a command line client for interacting with the Web Services API of
  the Hardware Management Console (HMC) of z Systems or LinuxONE machines.
  It allows management of LPARs, partitions and much more.

  The command line tool can be used in two modes:
  - Interactive shell (Read-eval-print loop)
  - Using a session
  - Always provide credentials

#### a) Example interactive shell:
```
   $ zhmc -h zhmc.example.com -u hmcuser repl
   <Provide password>
   > cpc list
   > partition list JLSE1
   > partition create JLSE1 --name TESTPART_JL --description "blablabla"
   --cp-processors 1 --initial-memory 4096 --maximum-memory 4096
   --processor-mode shared --boot-device test-operating-system
   > partition show JLSE1 TESTPART_JL
   > partition start JLSE1 TESTPART_JL
   > partition stop JLSE1 TESTPART_JL
   > partition delete JLSE1 TESTPART_JL --yes
   > :q
```
#### b) Example with a session:
```
   $ eval $(zhmc -h zhmc.example.com -u hmcuser session create)
   <Provide password>
   $ zhmc cpc list
   $ zhmc lpar list P0000P99
   $ zhmc lpar deactivate P0000P99 PART8 --yes
   $ zhmc --timestats lpar activate P0000P99 PART8
   $ zhmc lpar load P0000P99 PART8 5172
   $ zhmc lpar show P0000P99 PART8
   $ zhmc -o json lpar show P0000P30 PART8
   $ eval $(zhmc session delete --yes)
``` 
  The host, userid and session_id are stored in environment variables:
       ZHMC_HOST, ZHMC_USERID, ZHMC_SESSION_ID.

#### c) Examples providing always credentials:
```
  $ zhmc -h zhmc.example.com -u hmcuser cpc list
  $ zhmc -h zhmc.exampe.com api-version
  To get a list of available commands and options run:
  $ zhmc --help
  To get a list of sub-commands of commands and options run:
  $ zhmc session --help
  $ zhmc lpar --help
  $ zhmc partition --help
```

### CODE REVIEW

**Comment by mihajlov** [comment]
Two comments:
1. Storing the session key in the session.yaml file creates a security issue. I consider this to be a no go. A (functioning) key-ring should be used for that.
2. That may be a matter of taste or belief, but exposing the API's session concept increases the usage complexity without adding a tangible benefit.
You may want to consider to reuse the concepts for session credentials from my original proposal.

**Comment by mihajlov** [comment]
Clumsy me, I didn't want to close the request. Reopened.

**Comment by leopoldjuergen** [comment]
In the latest version credentials are not stored in a file. In REPL mode credentials are stored in memory and in the session mode in environment variables.

**Comment by andy-maier** [comment]
By accident, I have started a review ... anyway, it contains a few comments.

In addition, I have these comments:

* The usage line in the general help should better show the structure with resource & command, e.g.:

```
Usage: zhmc [GEN-OPTIONS] RESOURCE COMMAND [CMD-OPTIONS] [CMD-ARGS]
```

**Comment by andy-maier** [comment]
rebased

**Comment by andy-maier** [comment]
My commit from just now addresses those of my comments that could be solved. A number of comments related to the help text cannot be solved with the current `click` package.

The commit addresses quite a number of other issues in addition. For details, see its log message.

**Comment by andy-maier** [comment]
This PR is ready for another review.

**Comment by leopoldjuergen** [comment]
+1

**Pull request merged**
