### PR TITLE
Simplify quickstart example

### PR DESCRIPTION
**Pull request by leopoldjuergen**
Details:
- Updated example program in README.rst.

Signed-off-by: Juergen Leopold <leopoldj@de.ibm.com>

### CODE REVIEW

**Comment by leopoldjuergen** [comment]
+1

**Comment by andy-maier** [comment]
Please also simplify the (same) example code in the "Introduction" / "Examples" section of the documentation.

**Comment by leopoldjuergen** [comment]
Added to the  "Introduction" / "Examples" section section.

**Comment by andy-maier** [comment]
+1

**Pull request merged**
